#!/bin/bash

# Function: Print a help message.
display_help() {
	echo "snakeSV pipeline (powered by Snakemake)"
	echo ""
	echo "Usage: $0 --configfile FILE [Snakemake options]"
	echo ""
	echo " snakeSV custom parameters:"
  echo "   --test_run             run the full pipeline on a test data."
	echo ""
  echo " Useful Snakemake parameters:"
	echo "   --use-conda            use conda to automatically install pre-configured packages"
	echo "   -j, --cores            number of cores"
	echo "   -k, --keep-going       go on with independent jobs if a job fails"
	echo "   -n, --dryrun           do not execute anything"
	echo "   -p, --printshellcmds   print out the shell commands that will be executed"
	echo "   -t, --timestamp        add a timestamp to all logging output"
  echo ""
	echo " Full list of parameters:"
  echo "   --help                 show Snakemake help (or snakemake -h)"
	echo ""
	echo "More info at https://github.com/RajLabMSSM/snakeSV"
	echo ""
  exit 0
}

if [ "$1" == "--test_run" ]; then
    snakeSV --configfile $(dirname $(which snakeSV))/../opt/snakeSV/example/tiny/config.yaml \
          --config workdir="$(dirname $(which snakeSV))/../opt/snakeSV/example/tiny/files/" OUT_FOLDER="${PWD}/results_snakesv" \
          --cores 1 --use-conda --use-singularity -p
	exit 0
fi

if [ "$1" == "" -o "$1" == "-h" -o \( "$1" != "--configfile" -a "$1" != "--help" \) ]; then
  display_help
  exit 0
fi

snakemake -s workflow/Snakefile "$@"
